<?php

namespace Database\Seeders;

use App\Models\Buyer;
use App\Models\DriveType;
use App\Models\Manufacturer;
use App\Models\OwnerType;
use App\Models\Transmission;
use App\Models\VehicleModel;
use App\Models\VehicleType;
use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Illuminate\Support\Str;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'vin' => 'WVWZZZ1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Volkswagen')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'Golf')->first()->model_id,
                'first_registration' => '2020-05-15',
                'mileage' => 25000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Hatchback')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'FWD (Front-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Deep Black Pearl',
                'purchase_price' => 18000.00,
                'selling_price' => 22500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2024-05-15',
                'evaluation_date' => '2023-01-10',
                'last_edited_date' => now(),
                'days_on_stock' => 45,
                'seller_id' => 1,
                'status' => 'Available',
                'additional_info' => 'Well maintained, full service history.',
            ],
            [
                'vin' => 'WBAXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'BMW')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', '3 Series')->first()->model_id,
                'first_registration' => '2019-08-22',
                'mileage' => 35000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'RWD (Rear-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Alpine White',
                'purchase_price' => 25000.00,
                'selling_price' => 29500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Company Car')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2023-08-22',
                'evaluation_date' => '2023-02-15',
                'last_edited_date' => now(),
                'days_on_stock' => 30,
                'seller_id' => 2,
                'status' => 'Available',
                'additional_info' => 'Premium package, navigation system.',
            ],
            [
                'vin' => 'WAUZZZ8JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Audi')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'A4')->first()->model_id,
                'first_registration' => '2021-03-10',
                'mileage' => 15000,
                'transmission_id' => Transmission::where('type', 'Dual-Clutch')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'AWD (All-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Mythos Black',
                'purchase_price' => 32000.00,
                'selling_price' => 37500.00,
                'num_previous_owners' => 0,
                'owner_type_id' => OwnerType::where('type_name', 'Demo Vehicle')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2025-03-10',
                'evaluation_date' => '2023-03-05',
                'last_edited_date' => now(),
                'days_on_stock' => 20,
                'seller_id' => 3,
                'status' => 'Available',
                'additional_info' => 'S-Line package, virtual cockpit.',
            ],
            [
                'vin' => 'JHMXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Honda')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'Civic')->first()->model_id,
                'first_registration' => '2018-11-05',
                'mileage' => 45000,
                'transmission_id' => Transmission::where('type', 'CVT')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Hatchback')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'FWD (Front-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Rallye Red',
                'purchase_price' => 15000.00,
                'selling_price' => 18500.00,
                'num_previous_owners' => 2,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2024-11-05',
                'evaluation_date' => '2023-04-12',
                'last_edited_date' => now(),
                'days_on_stock' => 15,
                'seller_id' => 4,
                'status' => 'Available',
                'additional_info' => 'Sport trim, rear camera.',
            ],
            [
                'vin' => '5YJXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Tesla')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'Model 3')->first()->model_id,
                'first_registration' => '2022-01-20',
                'mileage' => 10000,
                'transmission_id' => Transmission::where('type', 'Single-Speed (Electric)')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'AWD (All-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Pearl White',
                'purchase_price' => 42000.00,
                'selling_price' => 48500.00,
                'num_previous_owners' => 0,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2026-01-20',
                'evaluation_date' => '2023-05-02',
                'last_edited_date' => now(),
                'days_on_stock' => 10,
                'seller_id' => 5,
                'status' => 'Available',
                'additional_info' => 'Long Range, Autopilot.',
            ],
            [
                'vin' => 'JTMXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Toyota')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'RAV4')->first()->model_id,
                'first_registration' => '2020-09-15',
                'mileage' => 30000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'SUV')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'AWD (All-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Blueprint',
                'purchase_price' => 24000.00,
                'selling_price' => 28500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2024-09-15',
                'evaluation_date' => '2023-06-10',
                'last_edited_date' => now(),
                'days_on_stock' => 5,
                'seller_id' => 1,
                'status' => 'Available',
                'additional_info' => 'Hybrid model, panoramic roof.',
            ],
            [
                'vin' => 'WVWZZZ2JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Volkswagen')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'Jetta')->first()->model_id,
                'first_registration' => '2019-05-20',
                'mileage' => 40000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'FWD (Front-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Platinum Gray',
                'purchase_price' => 16000.00,
                'selling_price' => 19500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2023-05-20',
                'evaluation_date' => '2023-01-15',
                'last_edited_date' => now(),
                'days_on_stock' => 60,
                'buyer_id' => Buyer::where('customer_number', 'B00001')->first()->customer_id,
                'customer_number' => 'B00001',
                'status' => 'Sold',
                'additional_info' => 'SEL Premium trim, leather seats.',
            ],
            [
                'vin' => 'WBAXXX2JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'BMW')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', '5 Series')->first()->model_id,
                'first_registration' => '2020-07-10',
                'mileage' => 25000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'AWD (All-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Carbon Black',
                'purchase_price' => 35000.00,
                'selling_price' => 41500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Company Car')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2024-07-10',
                'evaluation_date' => '2023-02-20',
                'last_edited_date' => now(),
                'days_on_stock' => 45,
                'buyer_id' => Buyer::where('customer_number', 'B00002')->first()->customer_id,
                'customer_number' => 'B00002',
                'status' => 'Sold',
                'additional_info' => 'M Sport package, premium sound system.',
            ],
            [
                'vin' => 'KMHXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Hyundai')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'Elantra')->first()->model_id,
                'first_registration' => '2021-04-05',
                'mileage' => 18000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'FWD (Front-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Intense Blue',
                'purchase_price' => 17000.00,
                'selling_price' => 20500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2025-04-05',
                'evaluation_date' => '2023-03-10',
                'last_edited_date' => now(),
                'days_on_stock' => 30,
                'buyer_id' => Buyer::where('customer_number', 'B00003')->first()->customer_id,
                'customer_number' => 'B00003',
                'status' => 'Sold',
                'additional_info' => 'Limited trim, sunroof.',
            ],
            [
                'vin' => 'WDDXXX1JZXW' . Str::random(6),
                'manufacturer_id' => Manufacturer::where('name', 'Mercedes-Benz')->first()->manufacturer_id,
                'model_id' => VehicleModel::where('model_name', 'C-Class')->first()->model_id,
                'first_registration' => '2019-10-15',
                'mileage' => 32000,
                'transmission_id' => Transmission::where('type', 'Automatic')->first()->transmission_id,
                'type_id' => VehicleType::where('type_name', 'Sedan')->first()->type_id,
                'drive_type_id' => DriveType::where('drive_type_name', 'RWD (Rear-Wheel Drive)')->first()->drive_type_id,
                'color' => 'Selenite Grey',
                'purchase_price' => 28000.00,
                'selling_price' => 33500.00,
                'num_previous_owners' => 1,
                'owner_type_id' => OwnerType::where('type_name', 'Private Owner')->first()->owner_type_id,
                'general_inspection_next_due_date' => '2023-10-15',
                'evaluation_date' => '2023-04-20',
                'last_edited_date' => now(),
                'days_on_stock' => 25,
                'status' => 'Reserved',
                'additional_info' => 'AMG Line, Burmester sound system.',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
